# Generated by Django 4.1.7 on 2023-03-23 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Natjecaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sudionik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Prijava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.DecimalField(decimal_places=2, max_digits=5)),
                ('natjecaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prijave', to='main.natjecaj')),
                ('sudionik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prijava', to='main.sudionik')),
            ],
        ),
        migrations.AddField(
            model_name='natjecaj',
            name='organizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natjecaji', to='main.organizator'),
        ),
    ]
