# Generated by Django 4.1.7 on 2023-03-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='natjecaj',
            old_name='datum',
            new_name='natjecaj_datum',
        ),
        migrations.RenameField(
            model_name='natjecaj',
            old_name='naziv',
            new_name='natjecaj_naziv',
        ),
        migrations.RenameField(
            model_name='natjecaj',
            old_name='organizator',
            new_name='natjecaj_organizator',
        ),
        migrations.RenameField(
            model_name='organizator',
            old_name='email',
            new_name='organizator_email',
        ),
        migrations.RenameField(
            model_name='organizator',
            old_name='naziv',
            new_name='organizator_naziv',
        ),
        migrations.RenameField(
            model_name='prijava',
            old_name='broj',
            new_name='prijava_broj',
        ),
        migrations.RenameField(
            model_name='prijava',
            old_name='natjecaj',
            new_name='prijava_natjecaj',
        ),
        migrations.RenameField(
            model_name='prijava',
            old_name='sudionik',
            new_name='prijava_sudionik',
        ),
        migrations.RenameField(
            model_name='sudionik',
            old_name='email',
            new_name='sudionik_email',
        ),
        migrations.RenameField(
            model_name='sudionik',
            old_name='naziv',
            new_name='sudionik_naziv',
        ),
    ]
