# Generated by Django 4.1.7 on 2023-03-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_prijava_prijava_broj'),
    ]

    operations = [
        migrations.AddField(
            model_name='natjecaj',
            name='natjecaj_sudionici',
            field=models.ManyToManyField(related_name='natjecaji', to='main.sudionik'),
        ),
    ]
